module.exports = {
  RISK_LEVELS: {
    LOW: 'LOW',
    MODERATE: 'MODERATE',
    HIGH: 'HIGH',
    CRITICAL: 'CRITICAL',
    EXTREME: 'EXTREME'
  },
  SENSOR_TYPES: {
    FLOOD: 'FLOOD_WATER_LEVEL',
    WILDFIRE: 'WILDFIRE_THERMAL',
    AIR_QUALITY: 'AIR_QUALITY_AQI',
    LANDSLIDE: 'LANDSLIDE_SOIL_MOISTURE',
    WEATHER: 'METEOROLOGICAL'
  },
  ALERT_STATUS: {
    ACTIVE: 'ACTIVE',
    ACKNOWLEDGED: 'ACKNOWLEDGED',
    RESOLVED: 'RESOLVED',
    FALSE_POSITIVE: 'FALSE_POSITIVE'
  },
  NOTIFICATION_CHANNELS: {
    EMAIL: 'EMAIL',
    SMS: 'SMS',
    PUSH: 'PUSH',
    SIREN: 'SIREN'
  },
  SYSTEM_ROLES: {
    ADMIN: 'ADMIN',
    OPERATOR: 'OPERATOR',
    ANALYST: 'ANALYST',
    FIELD_TECH: 'FIELD_TECH',
    PUBLIC_USER: 'PUBLIC_USER'
  }
};
